
version: 2.1

jobs:
  test-postgres:
    docker:
      - image: circleci/python:3.6.2-stretch
      - image: circleci/postgres:9.6.5-alpine-ram

    steps:
      - checkout
      - run:
          name: "Run Tests - Postgres"
          environment:
            CI_DBT_HOST: localhost
            CI_DBT_USER: root
            CI_DBT_PASS: ''
            CI_DBT_PORT: 5432
            CI_DBT_DBNAME: circle_test
          command: ./run_test.sh postgres

  test-snowflake:
    docker:
      - image: circleci/python:3.6.2-stretch

    steps:
      - checkout
      - run:
          name: "Run Tests - Snowflake"
          command: ./run_test.sh snowflake

  test-redshift:
    docker:
      - image: circleci/python:3.6.2-stretch

    steps:
      - checkout
      - run:
          name: "Run Tests - Redshift"
          command: ./run_test.sh redshift

  test-bigquery:
    docker:
      - image: circleci/python:3.6.2-stretch

    steps:
      - checkout
      - run:
          run: setup_creds
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json

      - run:
          name: "Run Tests - BigQuery"
          environment:
              GCLOUD_SERVICE_KEY_PATH: "/home/circleci/gcloud-service-key.json"
          command: ./run_test.sh bigquery

workflows:
  version: 2
  test-everything:
    jobs:
      - test-postgres

      - test-snowflake:
          filters: &no_forks
            branches:
              ignore: /pull\/[0-9]+/

      - test-bigquery:
          filters: *no_forks

      - test-redshift:
          filters: *no_forks

